ST-2 Implement the integration with XAPI
VirtoCommerce/vc-storefront pull request #581
Opened 2021-11-15 20:02 UTC by trueboroda

2021-11-16 05:52 UTC, Vectorfield4 submitted a review, later dismissed
Fix code smells, please.

2021-11-16 06:55 UTC, tatarincev requested changes

2021-11-16 06:55 UTC, tatarincev commented on Directory.Build.props
> +    <VersionSuffix>alpha-001</VersionSuffix>
Please remove this manul set version Tag

2021-11-18 10:51 UTC, tatarincev approved these changes

2021-11-18 11:12 UTC, merged