ST-13 Implement storefront CI.
VirtoCommerce/vc-storefront pull request #582
Opened 2021-11-19 15:01 UTC by trueboroda

Description: 

--

QA-test: 

Demo-test: 

Download artifact URL:

2021-11-22 07:34 UTC, ilyawzrd requested changes

2021-11-22 07:34 UTC, ilyawzrd commented on .github/workflows/main.yml
> +    # - name: Publish to Blob
Remove commented code

2021-11-22 10:54 UTC, Vectorfield4 submitted a review, later dismissed

2021-11-23 09:27 UTC, ilyawzrd approved these changes

2021-11-23 09:27 UTC, merged